name: Deploy Atlas

on:
  push:
    branches: [ "develop" ]
  pull_request:
  
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: export MONGODB_ATLAS_PRIVATE_KEY="e2b95834-277d-4d99-9f1d-f65fa53c1c83"
      - run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
