name: Deploy Atlas

on:
  push:
    branches: [ "develop" ]
  pull_request:
  
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        env:
          MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.ATLAS_ORG_ID }}
          MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}

      - run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
